ScrollReveal().reveal('.headline')
ScrollReveal().reveal('.tagline', { delay: 500 })
ScrollReveal().reveal('#contact', { delay: 1000 })
ScrollReveal().reveal('#work', { delay: 1500 })
ScrollReveal().reveal('#aboutme', { delay: 2000 })
